version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./backend:/app
    networks:
      - visual-whispers-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
        NEXT_PUBLIC_API_URL: http://localhost:8000 
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - visual-whispers-net

networks:
  visual-whispers-net:
    driver: bridge