version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
        TARGETARCH: ${ARCHITECTURE:-amd64}
    platform: linux/${ARCHITECTURE:-amd64}
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./backend:/app
      - backend_downloads:/app/downloads
    networks:
      - visual-whispers-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
        NODE_ENV: production
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000}
    platform: linux/${ARCHITECTURE:-amd64}
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
    depends_on:
      - backend
    networks:
      - visual-whispers-net

volumes:
  backend_downloads:

networks:
  visual-whispers-net:
    driver: bridge